"""Added  models

Revision ID: cc402763d26d
Revises: 2e1af49adac5
Create Date: 2023-07-17 12:29:01.379994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc402763d26d'
down_revision = '2e1af49adac5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
