"""add name to recipe

Revision ID: daf0bd9abd22
Revises: 8614d23c6b42
Create Date: 2023-07-17 14:35:39.522527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf0bd9abd22'
down_revision = '8614d23c6b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'name')
    # ### end Alembic commands ###
